# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/letv/s2/setup-makefiles.sh

VENDOR_PATH := vendor/leeco/s2

PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/sbin/qcrypto_module.hmac:root/sbin/qcrypto_module.hmac \
    $(VENDOR_PATH)/sbin/qcrypto_module.ko:root/sbin/qcrypto_module.ko \
    $(VENDOR_PATH)/sbin/qdrbg_module.hmac:root/sbin/qdrbg_module.hmac \
    $(VENDOR_PATH)/sbin/qdrbg_module.ko:root/sbin/qdrbg_module.ko \
    $(VENDOR_PATH)/sbin/qfintverify:root/sbin/qfintverify \
    $(VENDOR_PATH)/sbin/qfintverify.hmac:root/sbin/qfintverify.hmac

PRODUCT_COPY_FILES += \
	$(call find-copy-subdir-files,*,${LOCAL_PATH}/proprietary,system)
