# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/leeco/msm8996-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter zl1 x2,$(TARGET_DEVICE)),)

endif
