# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/leeco/x2/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/leeco/x2/proprietary/vendor/bin/qfp-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/qfp-daemon \
    vendor/leeco/x2/proprietary/vendor/etc/ad_calib_x2.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/ad_calib_x2.cfg \
    vendor/leeco/x2/proprietary/vendor/etc/camera/imx230_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_chromatix.xml \
    vendor/leeco/x2/proprietary/vendor/etc/camera/imx230_lg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_lg_chromatix.xml \
    vendor/leeco/x2/proprietary/vendor/etc/camera/imx230_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_sunny_chromatix.xml \
    vendor/leeco/x2/proprietary/vendor/etc/camera/msm8996_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/msm8996_camera.xml \
    vendor/leeco/x2/proprietary/vendor/etc/drc/drc_cfg_AZ.txt:$(TARGET_COPY_OUT_VENDOR)/etc/drc/drc_cfg_AZ.txt \
    vendor/leeco/x2/proprietary/vendor/etc/dts/dts-m6m8-lic.key:$(TARGET_COPY_OUT_VENDOR)/etc/dts/dts-m6m8-lic.key \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b00 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b01 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b02 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b03 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b04 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b05 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b06 \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mbn \
    vendor/leeco/x2/proprietary/vendor/firmware/cppf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mdt \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mbn \
    vendor/leeco/x2/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/leeco/x2/proprietary/vendor/etc/silence_short.wav:$(TARGET_COPY_OUT_VENDOR)/etc/silence_short.wav \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/leeco/x2/proprietary/vendor/etc/acdbdata/MTP/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/workspaceFile.qwsp \
    vendor/leeco/x2/proprietary/vendor/etc/qdcm_calib_data_le_x2_mdss_dsi_sharp_qhd_dualdsi_cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_le_x2_mdss_dsi_sharp_qhd_dualdsi_cmd.xml \
    vendor/leeco/x2/proprietary/vendor/etc/qdcm_calib_data_le_x2_mdss_dsi_truly_qhd_dualdsi_cmd_pvt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_le_x2_mdss_dsi_truly_qhd_dualdsi_cmd_pvt.xml \
    vendor/leeco/x2/proprietary/vendor/etc/qdcm_calib_data_mdss_dsi_sharp_qhd_dualdsi_cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mdss_dsi_sharp_qhd_dualdsi_cmd.xml \
    vendor/leeco/x2/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/leeco/x2/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/leeco/x2/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/leeco/x2/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/leeco/x2/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    vendor/leeco/x2/proprietary/vendor/firmware/cyccg.cybin:$(TARGET_COPY_OUT_VENDOR)/firmware/cyccg.cybin \
    vendor/leeco/x2/proprietary/vendor/firmware/cyccg_table.cybin:$(TARGET_COPY_OUT_VENDOR)/firmware/cyccg_table.cybin \
    vendor/leeco/x2/proprietary/vendor/firmware/sii6400_wihd_mhl.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/sii6400_wihd_mhl.fw \
    vendor/leeco/x2/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/leeco/x2/proprietary/vendor/lib/libSonyIMX230PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230PdafLibrary.so \
    vendor/leeco/x2/proprietary/vendor/lib/libSonyIMX230_lg_PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230_lg_PdafLibrary.so \
    vendor/leeco/x2/proprietary/vendor/lib/libSonyIMX230_sunny_PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230_sunny_PdafLibrary.so \
    vendor/leeco/x2/proprietary/vendor/lib/libactuator_bu63165.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu63165.so \
    vendor/leeco/x2/proprietary/vendor/lib/libactuator_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898122.so \
    vendor/leeco/x2/proprietary/vendor/lib/libactuator_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_1080p_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_1080p_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_1080p_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_1080p_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_4k_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_4k_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_4k_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_4k_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_common.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_hfr_240.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_liveshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_raw_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_raw_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_snapshot_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_video_4k.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_cpp_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_cpp_video_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_default_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_default_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_default_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_default_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_default_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hdr_snapshot_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hdr_snapshot_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hdr_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hdr_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_120_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_120_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_240.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_240_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_240_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_60_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_60_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_hfr_90_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_hfr_90_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_1080p_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_1080p_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_4k_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_4k_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_common.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_video_4k.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_default_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_default_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hdr_snapshot_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hdr_snapshot_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_120_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_120_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_60_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_60_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_postproc.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_snapshot_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_video_16M_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_video_16M_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_video_4k.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_zsl_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_zsl_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_postproc.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_1080p_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_1080p_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_4k_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_4k_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_hfr_240.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_liveshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_snapshot_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_cpp_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_cpp_video_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_default_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_default_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_default_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hdr_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hdr_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_240.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_240_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_240_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_hfr_90_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_hfr_90_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_video_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_zsl_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_zsl_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_raw_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_raw_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_raw_hdr_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_raw_hdr_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_lg_raw_hdr_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_lg_raw_hdr_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_snapshot_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_video_16M_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_video_16M_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_video_4k.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_video_hdr.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_zsl_preview_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_zsl_preview_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_imx230_zsl_video_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_zsl_video_lc898212xd.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_common.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_ds_chromatix.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_liveshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_us_chromatix.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_cpp_video_full.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_default_preview_dw9714.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_default_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_default_video_dw9714.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_120.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_120_dw9714.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_60.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_60_dw9714.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_90.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_hfr_90_dw9714.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_postproc.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_snapshot.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_video_full.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_zsl_preview.so \
    vendor/leeco/x2/proprietary/vendor/lib/libchromatix_ov8865_ofilm_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_ofilm_zsl_video.so \
    vendor/leeco/x2/proprietary/vendor/lib/libcppf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcppf.so \
    vendor/leeco/x2/proprietary/vendor/lib/libflash_i2c.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_i2c.so \
    vendor/leeco/x2/proprietary/vendor/lib/libmmcamera_imx230.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx230.so \
    vendor/leeco/x2/proprietary/vendor/lib/libmmcamera_imx230_lg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx230_lg.so \
    vendor/leeco/x2/proprietary/vendor/lib/libmmcamera_imx230_sunny.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx230_sunny.so \
    vendor/leeco/x2/proprietary/vendor/lib/libmmcamera_sony_imx230_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sony_imx230_eeprom.so \
    vendor/leeco/x2/proprietary/vendor/lib/libmmcamera_sony_imx230_plus_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sony_imx230_plus_eeprom.so \
    vendor/leeco/x2/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/leeco/x2/proprietary/vendor/lib/libois_bu63165.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_bu63165.so \
    vendor/leeco/x2/proprietary/vendor/lib/libois_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_lc898122.so \
    vendor/leeco/x2/proprietary/vendor/lib64/hw/fingerprint.qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.qcom.so \
    vendor/leeco/x2/proprietary/vendor/lib64/libmm-qdcm-diag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-qdcm-diag.so \
    vendor/leeco/x2/proprietary/vendor/lib64/libqfp-service.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqfp-service.so \
    vendor/leeco/x2/proprietary/vendor/lib64/qfp.wakeup.so:$(TARGET_COPY_OUT_VENDOR)/lib64/qfp.wakeup.so

PRODUCT_PACKAGES += \
    QFingerprintService
